### ISSUE TITLE
work with redux 2.0?

### ISSUE THREAD

**Issue by mjw56** [wbuchwalter/ng2-redux#1]
Hey, thinking of trying this out for ng2 project. Will this work with latest redux 2.0?

**Comment by wbuchwalter** [comment]
Hey Mike,
It won't currently work, there will be a release in the next few days which will support it and with an api very similar to ng-redux and less bugs :)

**Comment by mjw56** [comment]
Ok thanks :)

Maybe I'll just play around with 1.0.1 for the time being.

**Comment by wbuchwalter** [comment]
Hey Mike,
I just released [v2.0.0-alpha](https://www.npmjs.com/package/ng2-redux) which works with Redux 2.0.
Their will be breaking changes before the final release (`provide` and unsubscribing mostly) but you'll get a good idea of how this will works.
Let me know of things goes!
Thanks.

**Comment by mjw56** [comment]
Thanks for the quick turnaround William!

Will let you know how it goes. :)
