### ISSUE TITLE
Typescript complains about the reducer

### ISSUE THREAD

**Issue by Foxandxss** [wbuchwalter/ng2-redux#11]
In the counter example, we have our `reducer` like `Redux` explains us to have:

```javascript
export default (state:number = 0, action:any) => {
  ...
}
```

the problem is that Webstorm complains about having a required parameter after an optional one. It is not like it is optional, it is more as a default value in case of undefined.

Still, I guess it is right, we shouldn't do that (nor `Redux`) should do it.

Now my editor is all about red wiggles.

**Comment by wbuchwalter** [comment]
This is valid TS code with typescript 1.6, see [Default initializers on required parameters](https://github.com/Microsoft/TypeScript/pull/4022).
You probably just need to upgrade your TypeScript version. Not sure if webstorm supports 1.6 yet though.

**Comment by Foxandxss** [comment]
Oh, nice, one problem less.

**Comment by mpseidel** [comment]
@Foxandxss hey! Did you manage to make the error go away in webstorm? I have the latest WS11 installed which should support "the latest 1.6 features" but I get the same error on my reducer functions http://blog.jetbrains.com/webstorm/2015/11/webstorm-11-released/

**Comment by mpseidel** [comment]
@Foxandxss @wbuchwalter  ah no - seems this is not in 1.6 yet https://github.com/Microsoft/TypeScript/issues/4066
