### ISSUE TITLE
Bump to Angular 2 .37

### ISSUE THREAD

**Issue by Foxandxss** [wbuchwalter/ng2-redux#15]
The counter example doesn't work with .37.

Reducers are called, state changes but that change never hits the App component again so counter is always 0.

Tried to update it, but I think it is a problem with `ng2-redux` itself.

**Comment by wbuchwalter** [comment]
Hey!
Thanks for all your PRs.
Regarding this issue, I can't reproduce it.
The only change I had to do to have the example work with .37 is fix the event syntax on the counter component.
See the commit [here](https://github.com/wbuchwalter/ng2-redux/commit/3868f5ccf2ef5ca9340e38eb31a9ef7caf4f95d0)

**Comment by Foxandxss** [comment]
Let me try then

**Comment by Foxandxss** [comment]
That is odd, but a good odd.

**Comment by wbuchwalter** [comment]
:+1:
