### ISSUE TITLE
angular2/di has moved in latest ^2.0.0-alpha.46 version

### ISSUE THREAD

**Issue by vladimir-ivanov** [wbuchwalter/ng2-redux#17]
ERROR in ./~/ng2-redux/lib/components/provider.js
Module not found: Error: Cannot resolve module 'angular2/di' ...
needs to be either angular2/angular2 (which exportd angular2/core/di')

**Comment by wbuchwalter** [comment]
Thanks, updated and released as '2.0.0'

**Comment by vladimir-ivanov** [comment]
thank you, will give it a go today
