### ISSUE TITLE
ng2 alpha.53 support

### ISSUE THREAD

**Issue by lanocturne** [wbuchwalter/ng2-redux#19]
Hi @wbuchwalter 
Getting this ```
ERROR in ./~/ng2-redux/lib/components/provider.js
Module not found: Error: Cannot resolve module 'angular2/angular2' in ...node_modules/ng2-redux/lib/components
 @ ./~/ng2-redux/lib/components/provider.js 15:24-52 ``` when angular 2 version is .53

Any plan to fix this soon? Solution would be replace angular2/angular2 with angular2/core

**Comment by wbuchwalter** [comment]
Fixed in [2.0.2](https://github.com/wbuchwalter/ng2-redux/releases/tag/v2.0.2) release.
Thanks.
