### ISSUE TITLE
Router state

### ISSUE THREAD

**Issue by JonnyBGod** [wbuchwalter/ng2-redux#20]
Any plans to add router state like in ng-ui-router?

**Comment by wbuchwalter** [comment]
Hey João,
No plan for that at the moment on my side.
If anyone wants to start this, I'll be happy to recommend it in the doc / use it in samples.

Thanks.

**Comment by dagstuan** [comment]
Hey, I made a package with bindings between the Angular 2 RC-router and ng2-redux. you can find it here @JonnyBGod: https://www.npmjs.com/package/ng2-redux-router

**Comment by SethDavenport** [comment]
@dagstuan - I'll take a look!

@e-schultz ^
