### ISSUE TITLE
Latest version Angular2 - 2.0.0-alpha.37 removes "(^" syntax for events

### ISSUE THREAD

**Issue by meenie** [wbuchwalter/ng2-redux#8]
They've decided to bubble all events, so they've removed the `(^` syntax.  So in `./components/Counter.ts` the HTML should be:
```html
    <button (click)="increment()">+</button>
    <button (click)="decrement()">-</button>
    <button (click)="incrementIfOdd()">Increment if odd</button>
    <button (click)="incrementAsync()">Increment async</button>
```

**Comment by meenie** [comment]
I'll put in a PR later, after work.

**Comment by sectore** [comment]
NIce catch, thx! Just adding a pointer to these [BREAKING CHANGES](https://github.com/angular/angular/blob/2.0.0-alpha.37/CHANGELOG.md#breaking-changes) of Angular 2.0.0.-alpha.37
